import { useState } from 'react';
import {
  Box, Flex, Text, Heading, Input, Select, Switch, Button,
  IconButton, useToast, SimpleGrid, Code,
} from '@chakra-ui/react';
import {
  AddIcon, DeleteIcon, CopyIcon, DownloadIcon, CheckIcon,
  ChevronUpIcon, ChevronDownIcon, ArrowRightIcon,
} from '@chakra-ui/icons';
import { motion, AnimatePresence } from 'framer-motion';

const MotionBox = motion(Box);

// ── Colors ────────────────────────────────────────────────────────────────────
const ACCENT = '#63B3ED';
const GREEN  = '#68D391';
const RED    = '#FC8181';
const ORANGE = '#F6AD55';
const PURPLE = '#9F7AEA';
const CYAN   = '#76E4F7';

// ── Label ─────────────────────────────────────────────────────────────────────
const Label = ({ children }) => (
  <Text fontSize="10px" color="var(--dash-text-muted)" textTransform="uppercase"
    letterSpacing="wider" fontWeight="bold" mb={1.5}>{children}</Text>
);

// ── Input / Select styles ─────────────────────────────────────────────────────
const inputSx = {
  variant: 'unstyled', bg: 'rgba(255,255,255,0.05)',
  border: '1px solid rgba(255,255,255,0.1)', borderRadius: '10px',
  px: 4, h: '38px', fontSize: 'sm', color: 'var(--dash-text-primary)',
  _placeholder: { color: 'var(--dash-text-muted)' },
  _hover: { border: `1px solid ${ACCENT}50` },
  _focus: { border: `1px solid ${ACCENT}80`, boxShadow: `0 0 0 1px ${ACCENT}40` },
};
const selSx = {
  bg: 'rgba(255,255,255,0.05)', borderColor: 'rgba(255,255,255,0.1)',
  borderRadius: '10px', h: '38px', fontSize: 'sm', color: 'var(--dash-text-primary)',
  focusBorderColor: `${ACCENT}80`,
  _hover: { borderColor: `${ACCENT}50` },
  sx: { '& option': { background: '#1a1a1f !important' } },
};

// ── Card ──────────────────────────────────────────────────────────────────────
const Card = ({ children, accentColor = ACCENT, ...rest }) => (
  <Box pos="relative" bg="var(--dash-card-bg)" border="1px solid var(--dash-card-border)"
    borderRadius="14px" overflow="hidden" {...rest}>
    <Box pos="absolute" top="0" left="0" right="0" h="2px"
      style={{ background: `linear-gradient(to right, transparent, ${accentColor}80, transparent)` }} />
    {children}
  </Box>
);

// ── Stat card ─────────────────────────────────────────────────────────────────
const StatCard = ({ label, value, color, delay = 0 }) => (
  <MotionBox initial={{ opacity: 0, y: 10 }} animate={{ opacity: 1, y: 0 }}
    transition={{ duration: 0.22, delay }}
    px={4} py={3} borderRadius="12px" bg="var(--dash-card-bg)"
    border="1px solid var(--dash-card-border)" pos="relative" overflow="hidden">
    <Box pos="absolute" top={0} left={0} right={0} h="2px"
      style={{ background: `linear-gradient(to right, transparent, ${color}80, transparent)` }} />
    <Text fontSize="22px" fontWeight="bold" color={color} lineHeight={1}>{value}</Text>
    <Text fontSize="11px" color="var(--dash-text-muted)" mt={1}>{label}</Text>
  </MotionBox>
);

// ── Hop types ─────────────────────────────────────────────────────────────────
const HOP_TYPES = {
  beacon:     { label: 'Beacon / Implant',        color: ACCENT,  abbr: 'BCN' },
  socat:      { label: 'Socat TCP Redirect',       color: ORANGE,  abbr: 'SCT' },
  nginx:      { label: 'Nginx HTTPS Redirector',   color: GREEN,   abbr: 'NGX' },
  apache:     { label: 'Apache mod_rewrite',       color: ORANGE,  abbr: 'APT' },
  cloudflare: { label: 'Cloudflare Worker / CDN',  color: CYAN,    abbr: 'CF'  },
  lambda:     { label: 'AWS Lambda Serverless',    color: PURPLE,  abbr: 'λ'   },
  c2:         { label: 'Team Server / C2',         color: RED,     abbr: 'C2'  },
};

// ── Config generators ─────────────────────────────────────────────────────────
function genSocat(hop) {
  const lp = hop.listenPort || 443;
  const fh = hop.forwardHost || 'NEXT_HOP_IP';
  const fp = hop.forwardPort || 443;
  return `#!/bin/bash
# Socat TCP Redirector — ${hop.label || hop.id}
# Generated by Red Team Operations Center

# Install socat:
# apt install socat -y

# Foreground (testing):
socat TCP-LISTEN:${lp},reuseaddr,fork TCP:${fh}:${fp}

# Systemd service (production):
cat > /etc/systemd/system/redirector.service << 'EOF'
[Unit]
Description=Socat Redirector
After=network.target

[Service]
ExecStart=/usr/bin/socat TCP-LISTEN:${lp},reuseaddr,fork TCP:${fh}:${fp}
Restart=always
RestartSec=5

[Install]
WantedBy=multi-user.target
EOF

systemctl daemon-reload
systemctl enable --now redirector

# Firewall:
iptables -A INPUT  -p tcp --dport ${lp} -j ACCEPT
iptables -A OUTPUT -p tcp --dport ${fp} -j ACCEPT`;
}

function genNginx(hop) {
  const lp     = hop.listenPort  || 443;
  const fh     = hop.forwardHost || 'TEAM_SERVER_IP';
  const fp     = hop.forwardPort || 443;
  const domain = hop.domain      || 'redirector.example.com';
  const ah     = hop.authHeader  || 'X-Custom-Auth';
  const av     = hop.authValue   || 'ChangeMe123!';
  const uri    = hop.c2Profile   || '/jquery-3.3.1.min.js';
  const ahNorm = ah.replace(/-/g, '_');

  return `# Nginx HTTPS Redirector — ${hop.label || hop.id}
# /etc/nginx/sites-available/redirector

upstream c2_backend {
    server ${fh}:${fp} max_fails=3 fail_timeout=30s;
}

server {
    listen 80;
    server_name ${domain};
    return 301 https://$host$request_uri;
}

server {
    listen ${lp} ssl http2;
    server_name ${domain};

    ssl_certificate     /etc/letsencrypt/live/${domain}/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/${domain}/privkey.pem;
    ssl_protocols       TLSv1.2 TLSv1.3;
    ssl_ciphers         HIGH:!aNULL:!MD5;

    server_tokens off;
    add_header Server "Microsoft-IIS/10.0";

    # Layer 1: Block scanners by User-Agent
    if ($http_user_agent ~* (nmap|masscan|zgrab|shodan|censys|curl|python|go-http|ruby|nikto|sqlmap|nuclei)) {
        return 301 https://www.microsoft.com;
    }

    # Layer 2: Require custom auth header
    if ($http_${ahNorm} != "${av}") {
        return 301 https://www.microsoft.com;
    }

    # Layer 3: Only allow C2 URI paths
    location ~ ^${uri} {
        proxy_pass          https://c2_backend;
        proxy_ssl_verify    off;
        proxy_set_header    Host $host;
        proxy_set_header    X-Forwarded-For $remote_addr;
        proxy_set_header    ${ah} ${av};
        proxy_hide_header   X-Powered-By;
        proxy_connect_timeout 10s;
        proxy_read_timeout    30s;
    }

    # Layer 4: Catch-all redirect
    location / {
        return 301 https://www.microsoft.com;
    }
}`;
}

function genApache(hop) {
  const fh = hop.forwardHost || 'NEXT_HOP_IP';
  const fp = hop.forwardPort || 443;
  const ah = hop.authHeader  || 'X-Custom-Auth';
  const av = hop.authValue   || 'ChangeMe123!';
  return `# Apache mod_rewrite Redirector — ${hop.label || hop.id}
# a2enmod rewrite proxy proxy_http ssl headers

<VirtualHost *:443>
    SSLEngine on
    SSLCertificateFile    /etc/letsencrypt/live/DOMAIN/fullchain.pem
    SSLCertificateKeyFile /etc/letsencrypt/live/DOMAIN/privkey.pem

    ServerTokens Prod
    ServerSignature Off
    Header always set Server "Microsoft-IIS/10.0"

    SSLProxyEngine On
    SSLProxyVerify none
    SSLProxyCheckPeerCN off

    RewriteEngine On

    # Block bad user agents
    RewriteCond %{HTTP_USER_AGENT} (nmap|masscan|zgrab|shodan|censys|python|nikto|nuclei) [NC]
    RewriteRule .* https://www.microsoft.com/ [L,R=301]

    # Require custom auth header
    RewriteCond %{HTTP:${ah}} !^${av}$
    RewriteRule .* https://www.microsoft.com/ [L,R=301]

    # Block recon paths
    RewriteCond %{REQUEST_URI} \\.(php|asp|env|git|htaccess)$ [NC]
    RewriteRule .* https://www.microsoft.com/ [L,R=301]

    # Forward valid traffic
    RewriteRule ^(.*)$ https://${fh}:${fp}$1 [P,L]
    ProxyPassReverse / https://${fh}:${fp}/
</VirtualHost>`;
}

function genCloudflare(hop) {
  const fh = hop.forwardHost || 'NGINX_REDIRECTOR_IP';
  const fp = hop.forwardPort || 443;
  const ah = hop.authHeader  || 'X-Custom-Auth';
  const av = hop.authValue   || 'ChangeMe123!';
  return `// Cloudflare Worker — CDN Redirector
// Deploy: Workers & Pages → Create Worker
// Generated by Red Team Operations Center

const UPSTREAM  = 'https://${fh}:${fp}';
const AUTH_HDR  = '${ah}';
const AUTH_VAL  = '${av}';
const DECOY_URL = 'https://www.microsoft.com';

const BAD_UA = ['nmap','masscan','zgrab','shodan','censys','python','go-http','nuclei','nikto'];

export default {
  async fetch(request, env, ctx) {
    const ua = (request.headers.get('User-Agent') || '').toLowerCase();

    // Layer 1: UA filter
    if (BAD_UA.some(b => ua.includes(b)))
      return Response.redirect(DECOY_URL, 301);

    // Forward with auth header injected
    const url = new URL(request.url);
    url.hostname = '${fh}';

    const headers = new Headers(request.headers);
    headers.set(AUTH_HDR, AUTH_VAL);

    const req = new Request(url.toString(), {
      method:   request.method,
      headers,
      body:     ['GET','HEAD'].includes(request.method) ? undefined : request.body,
      redirect: 'manual',
    });

    try {
      const res = await fetch(req, { cf: { ssl: true } });
      const r   = new Response(res.body, res);
      r.headers.delete('X-Powered-By');
      r.headers.delete('Server');
      return r;
    } catch {
      return Response.redirect(DECOY_URL, 301);
    }
  },
};

/*
 * Dashboard settings:
 * Workers → Settings → Variables → AUTH_VAL = ${av} (Encrypted)
 * Workers → Triggers → Add Route: *.<your-domain>.com/* → this worker
 * DNS → Enable "Orange Cloud" (CDN proxy) on your A record
 * SSL/TLS → Full (strict)
 */`;
}

function genLambda(hop) {
  const fh = hop.forwardHost || 'NGINX_REDIRECTOR_IP';
  const fp = hop.forwardPort || 443;
  const ah = hop.authHeader  || 'X-Custom-Auth';
  const av = hop.authValue   || 'ChangeMe123!';
  return `# AWS Lambda Serverless Redirector — ${hop.label || hop.id}
# lambda_function.py

import urllib3

UPSTREAM = 'https://${fh}:${fp}'
AUTH_HDR = '${ah}'
AUTH_VAL = '${av}'
DECOY    = 'https://www.microsoft.com'
BAD_UA   = ['nmap','masscan','zgrab','shodan','python','nuclei']

http = urllib3.PoolManager(cert_reqs='CERT_NONE')

def lambda_handler(event, context):
    headers = event.get('headers') or {}
    ua = (headers.get('user-agent') or '').lower()

    if any(b in ua for b in BAD_UA):
        return {'statusCode': 301, 'headers': {'Location': DECOY}}

    path   = event.get('rawPath', '/')
    qs     = event.get('rawQueryString', '')
    method = event.get('requestContext', {}).get('http', {}).get('method', 'GET')
    body   = event.get('body', '')

    fwd = dict(headers)
    fwd[AUTH_HDR] = AUTH_VAL

    url  = f'{UPSTREAM}{path}{"?" + qs if qs else ""}'
    resp = http.request(method, url, headers=fwd, body=body or None, redirect=False)

    return {
        'statusCode': resp.status,
        'headers':    dict(resp.headers),
        'body':       resp.data.decode('utf-8', errors='replace'),
    }

# Deploy:
# zip lambda.zip lambda_function.py
# aws lambda create-function \\
#   --function-name c2-redirector \\
#   --runtime python3.11 \\
#   --role arn:aws:iam::ACCOUNT_ID:role/lambda-basic \\
#   --handler lambda_function.lambda_handler \\
#   --zip-file fileb://lambda.zip`;
}

function generateConfig(hop) {
  switch (hop.type) {
    case 'socat':      return genSocat(hop);
    case 'nginx':      return genNginx(hop);
    case 'apache':     return genApache(hop);
    case 'cloudflare': return genCloudflare(hop);
    case 'lambda':     return genLambda(hop);
    case 'beacon':
      return `# Beacon / Implant — ${hop.label || hop.id}
# Sleep:    ${hop.sleep || 60}s ± ${hop.jitter || 30}%
# Listener: ${hop.forwardHost || 'TEAM_SERVER_IP'}:${hop.listenPort || 443}
# Profile:  ${hop.c2Profile || 'default'}`;
    case 'c2':
      return `# Team Server / C2 — ${hop.label || hop.id}
# IP:      ${hop.forwardHost || 'TEAM_SERVER_IP'}
# Port:    ${hop.listenPort || 443}
# Profile: ${hop.c2Profile || 'default'}`;
    default: return '# No config for this hop type';
  }
}

// ── Visual diagram ────────────────────────────────────────────────────────────
function ChainDiagram({ hops, selectedId, onSelect }) {
  return (
    <Box overflowX="auto" py={2}>
      <Flex align="center" gap={0} minW="max-content">
        {hops.length === 0 && (
          <Text fontSize="12px" color="var(--dash-text-muted)">Add hops to build your chain</Text>
        )}
        {hops.map((hop, i) => {
          const ht = HOP_TYPES[hop.type] || HOP_TYPES.socat;
          const sel = selectedId === hop.id;
          const burned = hop.status === 'burned';
          return (
            <Flex key={hop.id} align="center" gap={0}>
              <Flex direction="column" align="center" gap={1}
                onClick={() => onSelect(hop.id)} cursor="pointer"
                opacity={burned ? 0.5 : 1} style={{ transition: 'opacity .15s' }}>
                <Box w="52px" h="52px" borderRadius="10px"
                  border="2px solid" borderColor={sel ? 'white' : ht.color}
                  bg={sel ? `${ht.color}20` : 'rgba(255,255,255,0.04)'}
                  display="flex" alignItems="center" justifyContent="center"
                  pos="relative" style={{ transition: 'all .15s' }}>
                  <Text fontSize="9px" fontWeight="800" color={ht.color}
                    letterSpacing="0.05em">{ht.abbr}</Text>
                  {burned && (
                    <Box pos="absolute" top="-4px" right="-4px" w="10px" h="10px"
                      borderRadius="full" bg={RED} />
                  )}
                </Box>
                <Text fontSize="9px" color={sel ? 'var(--dash-text-primary)' : 'var(--dash-text-muted)'}
                  maxW="56px" textAlign="center" noOfLines={2} lineHeight="1.3">
                  {hop.label || ht.abbr}
                </Text>
                {hop.listenPort && (
                  <Text fontSize="8px" color="var(--dash-text-muted)">:{hop.listenPort}</Text>
                )}
              </Flex>
              {i < hops.length - 1 && (
                <Flex align="center" mx={1} mt="-18px">
                  <Box h="1px" w="28px"
                    bg={burned ? `${RED}60` : 'rgba(255,255,255,0.15)'} />
                  <ArrowRightIcon color={burned ? `${RED}60` : 'var(--dash-text-muted)'} boxSize={2} />
                </Flex>
              )}
            </Flex>
          );
        })}
      </Flex>
    </Box>
  );
}

// ── Hop row ───────────────────────────────────────────────────────────────────
function HopRow({ hop, idx, total, onChange, onDelete, selected, onSelect, onMove }) {
  const ht     = HOP_TYPES[hop.type] || HOP_TYPES.socat;
  const burned = hop.status === 'burned';
  const set    = (k, v) => onChange({ ...hop, [k]: v });
  const [exp, setExp] = useState(false);

  const hasForward = ['socat','nginx','apache','cloudflare','lambda'].includes(hop.type);
  const hasAuth    = ['nginx','apache','cloudflare','lambda'].includes(hop.type);
  const hasDomain  = ['nginx','apache','cloudflare'].includes(hop.type);

  return (
    <MotionBox initial={{ opacity: 0, x: -8 }} animate={{ opacity: 1, x: 0 }}
      transition={{ duration: 0.18 }}
      pos="relative" bg="var(--dash-card-bg)"
      border="1px solid"
      borderColor={selected ? `${ht.color}60` : 'var(--dash-card-border)'}
      borderRadius="12px" overflow="hidden"
      opacity={burned ? 0.7 : 1}
      style={{ transition: 'border-color 0.15s, opacity 0.15s' }}>
      <Box pos="absolute" top="0" left="0" right="0" h="2px"
        style={{ background: `linear-gradient(to right, transparent, ${ht.color}80, transparent)` }} />

      {/* Header row */}
      <Flex px={4} py={3} align="center" gap={3} cursor="pointer"
        onClick={() => { onSelect(hop.id); setExp(e => !e); }}>
        <Flex w="32px" h="32px" borderRadius="8px" flexShrink={0}
          bg={`${ht.color}12`} border={`1px solid ${ht.color}30`}
          align="center" justify="center">
          <Text fontSize="8px" fontWeight="800" color={ht.color}
            letterSpacing="0.05em">{ht.abbr}</Text>
        </Flex>
        <Box flex={1} minW={0}>
          <Text fontSize="13px" fontWeight="bold" color="var(--dash-text-primary)" noOfLines={1}>
            {hop.label || ht.label}
          </Text>
          <Text fontSize="10px" color="var(--dash-text-muted)">
            {hop.domain || hop.forwardHost
              ? `${hop.domain || hop.forwardHost}${hop.listenPort ? `:${hop.listenPort}` : ''}`
              : ht.label}
          </Text>
        </Box>
        <Flex align="center" gap={1.5} px={2} py="3px" borderRadius="6px"
          bg={burned ? `${RED}15` : `${GREEN}15`}
          border={burned ? `1px solid ${RED}40` : `1px solid ${GREEN}40`}
          flexShrink={0}>
          <Box w="5px" h="5px" borderRadius="full" bg={burned ? RED : GREEN}
            boxShadow={burned ? 'none' : `0 0 5px ${GREEN}`} />
          <Text fontSize="9px" fontWeight="700" color={burned ? RED : GREEN}
            textTransform="uppercase" letterSpacing="wider">
            {burned ? 'Burned' : 'Active'}
          </Text>
        </Flex>
        <Flex gap={0.5} onClick={e => e.stopPropagation()}>
          <IconButton icon={<ChevronUpIcon boxSize={3} />} size="xs" variant="ghost"
            color="var(--dash-text-muted)" _hover={{ color: 'white' }}
            isDisabled={idx === 0} aria-label="Move up"
            onClick={() => onMove(idx, -1)} />
          <IconButton icon={<ChevronDownIcon boxSize={3} />} size="xs" variant="ghost"
            color="var(--dash-text-muted)" _hover={{ color: 'white' }}
            isDisabled={idx === total - 1} aria-label="Move down"
            onClick={() => onMove(idx, 1)} />
          <IconButton icon={<DeleteIcon boxSize={3} />} size="xs" variant="ghost"
            color="var(--dash-text-muted)" _hover={{ color: RED, bg: `${RED}10` }}
            aria-label="Delete" onClick={() => onDelete(hop.id)} />
        </Flex>
      </Flex>

      {/* Expanded form */}
      {exp && (
        <Box px={4} pb={4} borderTop="1px solid rgba(255,255,255,0.06)">
          <SimpleGrid columns={2} gap={3} mt={3}>
            <Box>
              <Label>Label</Label>
              <Input value={hop.label} onChange={e => set('label', e.target.value)}
                placeholder="Hop label" {...inputSx} size="sm" />
            </Box>
            <Box>
              <Label>Type</Label>
              <Select value={hop.type} onChange={e => set('type', e.target.value)} {...selSx} size="sm">
                {Object.entries(HOP_TYPES).map(([k, v]) => (
                  <option key={k} value={k}>{v.label}</option>
                ))}
              </Select>
            </Box>
          </SimpleGrid>

          {hasDomain && (
            <Box mt={3}>
              <Label>Domain</Label>
              <Input value={hop.domain || ''} onChange={e => set('domain', e.target.value)}
                placeholder="redirector.example.com" {...inputSx} size="sm" />
            </Box>
          )}

          <SimpleGrid columns={hasForward ? 3 : 1} gap={3} mt={3}>
            <Box>
              <Label>Listen Port</Label>
              <Input type="number" value={hop.listenPort || ''}
                onChange={e => set('listenPort', e.target.value)}
                placeholder="443" {...inputSx} size="sm" />
            </Box>
            {hasForward && <>
              <Box>
                <Label>Forward Host</Label>
                <Input value={hop.forwardHost || ''} onChange={e => set('forwardHost', e.target.value)}
                  placeholder="10.0.0.1" fontFamily="monospace" fontSize="12px" {...inputSx} size="sm" />
              </Box>
              <Box>
                <Label>Forward Port</Label>
                <Input type="number" value={hop.forwardPort || ''}
                  onChange={e => set('forwardPort', e.target.value)}
                  placeholder="443" {...inputSx} size="sm" />
              </Box>
            </>}
          </SimpleGrid>

          {hasAuth && (
            <SimpleGrid columns={2} gap={3} mt={3}>
              <Box>
                <Label>Auth Header Name</Label>
                <Input value={hop.authHeader || ''} onChange={e => set('authHeader', e.target.value)}
                  placeholder="X-Custom-Auth" fontFamily="monospace" fontSize="12px" {...inputSx} size="sm" />
              </Box>
              <Box>
                <Label>Auth Header Value</Label>
                <Input value={hop.authValue || ''} onChange={e => set('authValue', e.target.value)}
                  placeholder="SecretValue123" fontFamily="monospace" fontSize="12px" {...inputSx} size="sm" />
              </Box>
            </SimpleGrid>
          )}

          {hop.type === 'nginx' && (
            <Box mt={3}>
              <Label>C2 URI Pattern</Label>
              <Input value={hop.c2Profile || ''} onChange={e => set('c2Profile', e.target.value)}
                placeholder="/jquery-3.3.1.min.js" fontFamily="monospace" fontSize="12px" {...inputSx} size="sm" />
            </Box>
          )}

          {hop.type === 'beacon' && (
            <SimpleGrid columns={2} gap={3} mt={3}>
              <Box>
                <Label>Sleep (seconds)</Label>
                <Input type="number" value={hop.sleep || ''}
                  onChange={e => set('sleep', e.target.value)} placeholder="60" {...inputSx} size="sm" />
              </Box>
              <Box>
                <Label>Jitter (%)</Label>
                <Input type="number" value={hop.jitter || ''}
                  onChange={e => set('jitter', e.target.value)} placeholder="30" {...inputSx} size="sm" />
              </Box>
            </SimpleGrid>
          )}

          <Flex align="center" gap={2} mt={4}>
            <Switch size="sm" colorScheme="green"
              isChecked={hop.status !== 'burned'}
              onChange={e => set('status', e.target.checked ? 'active' : 'burned')} />
            <Text fontSize="11px" color={burned ? RED : GREEN} fontWeight="semibold">
              {burned ? 'Burned — mark active to re-enable' : 'Active'}
            </Text>
          </Flex>
        </Box>
      )}
    </MotionBox>
  );
}

// ── Config panel ──────────────────────────────────────────────────────────────
function ConfigPanel({ hop }) {
  const toast = useToast();
  const [copied, setCopied] = useState(false);

  if (!hop) return (
    <Card accentColor={ACCENT} h="100%">
      <Flex direction="column" align="center" justify="center" h="100%" py={16} gap={3}>
        <Box w="40px" h="40px" borderRadius="10px"
          bg={`${ACCENT}12`} border={`1px solid ${ACCENT}30`}
          display="flex" alignItems="center" justifyContent="center">
          <Text fontSize="16px" color={ACCENT}>⚡</Text>
        </Box>
        <Text fontSize="13px" fontWeight="semibold" color="var(--dash-text-secondary)">
          Select a hop to view config
        </Text>
        <Text fontSize="11px" color="var(--dash-text-muted)" textAlign="center" maxW="220px">
          Click any hop in the list or diagram to generate its configuration
        </Text>
      </Flex>
    </Card>
  );

  const ht     = HOP_TYPES[hop.type] || HOP_TYPES.socat;
  const config = generateConfig(hop);
  const ext    = hop.type === 'cloudflare' ? 'js' : hop.type === 'lambda' ? 'py' : hop.type === 'nginx' ? 'conf' : 'sh';

  const copy = () => {
    navigator.clipboard.writeText(config);
    setCopied(true);
    setTimeout(() => setCopied(false), 1500);
    toast({ title: 'Config copied', status: 'success', duration: 2000, isClosable: true });
  };

  const download = () => {
    const blob = new Blob([config], { type: 'text/plain' });
    const a = document.createElement('a');
    a.href = URL.createObjectURL(blob);
    a.download = `${hop.label || hop.type}.${ext}`;
    a.click();
  };

  return (
    <Card accentColor={ht.color} display="flex" flexDirection="column" h="100%">
      {/* Header */}
      <Flex px={5} py={4} align="center" justify="space-between"
        borderBottom="1px solid rgba(255,255,255,0.06)">
        <Flex align="center" gap={3}>
          <Flex w="30px" h="30px" borderRadius="8px"
            bg={`${ht.color}12`} border={`1px solid ${ht.color}30`}
            align="center" justify="center" flexShrink={0}>
            <Text fontSize="8px" fontWeight="800" color={ht.color}
              letterSpacing="0.05em">{ht.abbr}</Text>
          </Flex>
          <Box>
            <Text fontSize="13px" fontWeight="bold" color="var(--dash-text-primary)">
              {hop.label || ht.label}
            </Text>
            <Text fontSize="10px" color="var(--dash-text-muted)">{ht.label} · {ext}</Text>
          </Box>
        </Flex>
        <Flex gap={1.5}>
          <Button size="xs" leftIcon={copied ? <CheckIcon /> : <CopyIcon />}
            variant="ghost" color="var(--dash-text-muted)" borderRadius="6px"
            border="1px solid rgba(255,255,255,0.1)"
            _hover={{ color: 'white', bg: 'rgba(255,255,255,0.06)' }}
            onClick={copy}>
            {copied ? 'Copied!' : 'Copy'}
          </Button>
          <Button size="xs" leftIcon={<DownloadIcon />} borderRadius="6px"
            bg={`${ht.color}15`} color={ht.color} border={`1px solid ${ht.color}35`}
            _hover={{ bg: `${ht.color}28` }} fontWeight="bold"
            onClick={download}>
            Download
          </Button>
        </Flex>
      </Flex>

      {/* File tab bar */}
      <Flex px={5} py={2} align="center" gap={2}
        bg="rgba(0,0,0,0.2)" borderBottom="1px solid rgba(255,255,255,0.05)">
        <Flex w={2.5} h={2.5} borderRadius="full" bg="red.400" />
        <Flex w={2.5} h={2.5} borderRadius="full" bg="yellow.400" />
        <Flex w={2.5} h={2.5} borderRadius="full" bg="green.400" />
        <Text fontSize="11px" color="var(--dash-text-muted)" ml={2} fontFamily="monospace">
          {hop.label || hop.type}.{ext}
        </Text>
      </Flex>

      {/* Code */}
      <Box flex={1} overflow="auto" bg="rgba(0,0,0,0.35)" p={5}
        sx={{ '&::-webkit-scrollbar': { w: '3px' }, '&::-webkit-scrollbar-thumb': { bg: 'rgba(255,255,255,0.1)', borderRadius: '3px' } }}>
        <Code display="block" bg="transparent" color="#e6edf3"
          fontSize="11px" fontFamily="'Fira Code','Consolas',monospace"
          whiteSpace="pre" lineHeight="1.7">
          {config}
        </Code>
      </Box>
    </Card>
  );
}

// ── Default chain ─────────────────────────────────────────────────────────────
const DEFAULT_CHAIN = [
  { id: 'h1', type: 'beacon',     label: 'Implant',           listenPort: '',  forwardHost: '',             status: 'active', sleep: 60, jitter: 30 },
  { id: 'h2', type: 'cloudflare', label: 'CF Worker',         listenPort: 443, forwardHost: '',             domain: 'cdn.example.com',   authHeader: 'X-Custom-Auth', authValue: 'RedTeam2024!', status: 'active' },
  { id: 'h3', type: 'nginx',      label: 'HTTPS Redirector',  listenPort: 443, forwardHost: '',             domain: 'redir.example.com', authHeader: 'X-Custom-Auth', authValue: 'RedTeam2024!', c2Profile: '/jquery-3.3.1.min.js', status: 'active' },
  { id: 'h4', type: 'c2',         label: 'Team Server',       listenPort: 443, forwardHost: '10.10.0.204',  status: 'active' },
];

let _nid = 10;
const nextId = () => `h${_nid++}`;

// ── Main ──────────────────────────────────────────────────────────────────────
export default function RedirectorChainView() {
  const toast = useToast();
  const [hops,        setHops]        = useState(DEFAULT_CHAIN);
  const [selectedId,  setSelectedId]  = useState('h3');
  const [chainName,   setChainName]   = useState('Primary Redirector Chain');
  const [chainActive, setChainActive] = useState(true);
  const [newType,     setNewType]     = useState('');

  const selectedHop = hops.find(h => h.id === selectedId) || null;
  const activeCnt   = hops.filter(h => h.status !== 'burned').length;
  const burnedCnt   = hops.filter(h => h.status === 'burned').length;

  const addHop = (type) => {
    if (!type) return;
    const ht  = HOP_TYPES[type];
    const hop = {
      id: nextId(), type, label: ht.label,
      listenPort: 443, forwardHost: '', domain: '',
      authHeader: 'X-Custom-Auth', authValue: 'ChangeMe123!',
      c2Profile: '/jquery-3.3.1.min.js', status: 'active',
    };
    setHops(prev => [...prev, hop]);
    setSelectedId(hop.id);
    setNewType('');
  };

  const updateHop = (updated) =>
    setHops(prev => prev.map(h => h.id === updated.id ? updated : h));

  const deleteHop = (id) => {
    setHops(prev => {
      const next = prev.filter(h => h.id !== id);
      if (selectedId === id) setSelectedId(next[0]?.id || null);
      return next;
    });
  };

  const moveHop = (idx, dir) => {
    setHops(prev => {
      const arr  = [...prev];
      const tgt  = idx + dir;
      if (tgt < 0 || tgt >= arr.length) return arr;
      [arr[idx], arr[tgt]] = [arr[tgt], arr[idx]];
      return arr;
    });
  };

  const downloadAll = () => {
    hops.forEach(hop => {
      const cfg = generateConfig(hop);
      const ext = hop.type === 'cloudflare' ? 'js' : hop.type === 'lambda' ? 'py' : hop.type === 'nginx' ? 'conf' : 'sh';
      const blob = new Blob([cfg], { type: 'text/plain' });
      const a = document.createElement('a');
      a.href = URL.createObjectURL(blob);
      a.download = `${hop.label || hop.type}.${ext}`;
      a.click();
    });
    toast({ title: `${hops.length} config files downloaded`, status: 'success', duration: 2000 });
  };

  // OPSEC checks
  const opsec = [
    { label: 'CDN layer present',        ok: hops.some(h => h.type === 'cloudflare') },
    { label: 'Auth header chaining',     ok: hops.some(h => h.authHeader) },
    { label: 'HTTPS redirector (nginx/apache)', ok: hops.some(h => ['nginx','apache'].includes(h.type)) },
    { label: 'Beacon sleep ≥ 30s',      ok: hops.some(h => h.type === 'beacon' && Number(h.sleep) >= 30) },
    { label: 'Multi-hop chain (≥ 3)',   ok: hops.length >= 3 },
    { label: 'No burned hops',          ok: burnedCnt === 0 },
  ];
  const opsecScore = opsec.filter(o => o.ok).length;

  return (
    <Box px={6} pb={12} pt={5}>

      {/* ── Header ────────────────────────────────────────────────────────── */}
      <Flex justify="space-between" align="flex-start" mb={5} flexWrap="wrap" gap={3}>
        <Box>
          <Heading fontSize="2xl" fontWeight="bold" color="var(--dash-text-primary)" lineHeight={1.2}>
            Redirector <Text as="span" color="red.400">Chain Planner</Text>
          </Heading>
          <Text fontSize="12px" color="var(--dash-text-secondary)" mt={1}>
            Design multi-hop redirector chains · generate exact configs per hop · track active vs burned
          </Text>
        </Box>
        <Button size="sm" leftIcon={<DownloadIcon />} borderRadius="8px"
          bg={`${ACCENT}20`} color={ACCENT} border={`1px solid ${ACCENT}50`}
          _hover={{ bg: `${ACCENT}35` }} fontWeight="bold" fontSize="12px"
          onClick={downloadAll}>
          Export All Configs
        </Button>
      </Flex>

      {/* ── Info banner ───────────────────────────────────────────────────── */}
      <Box mb={5} px={4} py={3} borderRadius="10px"
        bg="rgba(99,179,237,0.07)" border="1px solid rgba(99,179,237,0.25)">
        <Flex align="center" gap={2} mb={1.5}>
          <Box w="6px" h="6px" borderRadius="full" bg={ACCENT} />
          <Text fontSize="10px" fontWeight="bold" color={ACCENT}
            textTransform="uppercase" letterSpacing="wider">Architecture</Text>
        </Flex>
        <Flex gap={4} flexWrap="wrap">
          {[
            'Beacon → CDN (Cloudflare Worker) → HTTPS Redirector (Nginx/Apache) → Team Server',
            'Custom auth headers chain hops together and block automated scanners',
            'Mark hops as burned when detected — track OPSEC posture per chain',
          ].map(t => (
            <Flex key={t} align="center" gap={1.5}>
              <Box w="4px" h="4px" borderRadius="full" bg={ACCENT} flexShrink={0} />
              <Text fontSize="11px" color="var(--dash-text-secondary)">{t}</Text>
            </Flex>
          ))}
        </Flex>
      </Box>

      {/* ── Stat row ──────────────────────────────────────────────────────── */}
      <SimpleGrid columns={4} gap={4} mb={6}>
        <StatCard label="Total Hops"   value={hops.length}  color={ACCENT}  delay={0} />
        <StatCard label="Active"        value={activeCnt}    color={GREEN}   delay={0.04} />
        <StatCard label="Burned"        value={burnedCnt}    color={RED}     delay={0.08} />
        <StatCard label="OPSEC Score"   value={`${opsecScore}/${opsec.length}`} color={opsecScore >= 5 ? GREEN : opsecScore >= 3 ? ORANGE : RED} delay={0.12} />
      </SimpleGrid>

      {/* ── Chain diagram ─────────────────────────────────────────────────── */}
      <Card mb={6} accentColor={ACCENT}>
        <Box px={5} py={4}>
          <Flex align="center" justify="space-between" mb={4}>
            <Flex align="center" gap={3}>
              <Input value={chainName} onChange={e => setChainName(e.target.value)}
                variant="unstyled" fontSize="13px" fontWeight="bold"
                color="var(--dash-text-primary)" w="260px"
                _placeholder={{ color: 'var(--dash-text-muted)' }} />
              <Flex align="center" gap={2}>
                <Switch size="sm" colorScheme="green"
                  isChecked={chainActive} onChange={e => setChainActive(e.target.checked)} />
                <Text fontSize="11px" fontWeight="semibold"
                  color={chainActive ? GREEN : RED}>
                  {chainActive ? 'Active' : 'Burned'}
                </Text>
              </Flex>
            </Flex>
            <Flex align="center" gap={2}>
              <Select value={newType} onChange={e => { addHop(e.target.value); }}
                placeholder="+ Add hop" size="sm" w="160px"
                bg="rgba(255,255,255,0.05)" borderColor="rgba(255,255,255,0.1)"
                borderRadius="8px" fontSize="12px" color="var(--dash-text-primary)"
                _hover={{ borderColor: `${ACCENT}50` }}
                focusBorderColor={`${ACCENT}80`}
                sx={{ '& option': { background: '#1a1a1f !important' } }}>
                {Object.entries(HOP_TYPES).map(([k, v]) => (
                  <option key={k} value={k}>{v.label}</option>
                ))}
              </Select>
            </Flex>
          </Flex>
          <ChainDiagram hops={hops} selectedId={selectedId} onSelect={setSelectedId} />
        </Box>
      </Card>

      {/* ── Main: hop list + config ────────────────────────────────────────── */}
      <Flex gap={6} align="flex-start">

        {/* Left: hop list + OPSEC */}
        <Box w="380px" flexShrink={0}>
          <Text fontSize="10px" color="var(--dash-text-muted)" textTransform="uppercase"
            letterSpacing="wider" fontWeight="bold" mb={3}>
            Hops ({hops.length})
          </Text>

          <Flex direction="column" gap={3} mb={4}>
            <AnimatePresence>
              {hops.map((hop, i) => (
                <HopRow key={hop.id} hop={hop} idx={i} total={hops.length}
                  onChange={updateHop} onDelete={deleteHop}
                  selected={selectedId === hop.id}
                  onSelect={setSelectedId}
                  onMove={moveHop} />
              ))}
            </AnimatePresence>
            {hops.length === 0 && (
              <Box px={5} py={8} borderRadius="12px" textAlign="center"
                bg="var(--dash-card-bg)" border="1px solid var(--dash-card-border)">
                <Text fontSize="12px" color="var(--dash-text-muted)">
                  No hops yet — add one from the chain diagram above
                </Text>
              </Box>
            )}
          </Flex>

          {/* OPSEC checklist */}
          <Card accentColor={opsecScore >= 5 ? GREEN : ORANGE}>
            <Box p={5}>
              <Flex align="center" justify="space-between" mb={3}>
                <Label>OPSEC Checklist</Label>
                <Flex align="center" gap={1.5} px={2} py="2px" borderRadius="5px"
                  bg={opsecScore >= 5 ? `${GREEN}15` : `${ORANGE}15`}
                  border={opsecScore >= 5 ? `1px solid ${GREEN}40` : `1px solid ${ORANGE}40`}>
                  <Text fontSize="9px" fontWeight="bold"
                    color={opsecScore >= 5 ? GREEN : ORANGE}>
                    {opsecScore}/{opsec.length}
                  </Text>
                </Flex>
              </Flex>
              <Flex direction="column" gap={2}>
                {opsec.map((item, i) => (
                  <Flex key={i} align="center" gap={2.5}
                    py={1.5} borderBottom={i < opsec.length - 1 ? '1px solid rgba(255,255,255,0.05)' : 'none'}>
                    <Flex w="16px" h="16px" borderRadius="4px" flexShrink={0}
                      bg={item.ok ? `${GREEN}15` : 'rgba(255,255,255,0.05)'}
                      border={item.ok ? `1px solid ${GREEN}40` : '1px solid rgba(255,255,255,0.1)'}
                      align="center" justify="center">
                      {item.ok && <CheckIcon boxSize={2} color={GREEN} />}
                    </Flex>
                    <Text fontSize="11px" color={item.ok ? 'var(--dash-text-primary)' : 'var(--dash-text-muted)'}>
                      {item.label}
                    </Text>
                  </Flex>
                ))}
              </Flex>
            </Box>
          </Card>
        </Box>

        {/* Right: config viewer */}
        <Box flex={1} minW={0} minH="600px">
          <ConfigPanel hop={selectedHop} />
        </Box>
      </Flex>
    </Box>
  );
}
